test:
  stage: test
  image: git.e-conomix.at:5050/cors/docker/php-alpine-3.18-cli:8.1-5.0.0
  variables:
    DATABASE_HOST: ""
    DATABASE_PORT: ""
    DATABASE_USER: ""
    DATABASE_PASSWORD: ""
    DATABASE_NAME: ""
    DATABASE_VERSION: "8.0.26"
  cache:
    paths:
      - vendor/
  before_script:
    - composer install
  script:
    - vendor/bin/ecs check src --fix
    - vendor/bin/phpstan analyse src
    - vendor/bin/psalm src
  tags:
    - cors