version: '3.4'

networks:
  cors_dev:
    external: true

services:
  db:
    image: mysql:8
    container_name: cors_prometheus
    networks:
      - cors_dev
    working_dir: /application
    volumes:
      - cors-prometheus-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

  nginx:
    image: nginx:stable-alpine
    container_name: cors-prometheus-nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.cors_prometheus.rule=Host(`cors-prometheus.localhost`)
      - traefik.http.routers.cors_prometheus.entrypoints=cors_dev
      - traefik.http.routers.cors_prometheus.tls=true
      - traefik.http.services.cors_prometheus.loadbalancer.server.port=80
      - traefik.docker.network=cors_dev
    networks:
      - cors_dev
    volumes:
      - ./:/var/www/html:ro
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - php-debug

  php:
    image: git.e-conomix.at:5050/cors/docker/php-alpine-3.18-fpm:8.1-5.0.0
    container_name: php-cors-prometheus
    command: 'php-fpm'
    entrypoint: docker-php-entrypoint
    networks:
      - cors_dev
    depends_on:
      - db
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-additional.ini:ro
    environment:
      - COMPOSER_AUTH=${COMPOSER_AUTH}

  php-debug:
    image: git.e-conomix.at:5050/cors/docker/php-alpine-3.18-fpm-debug:8.1-5.0.0
    command: 'php-fpm'
    entrypoint: xdebug-entrypoint
    container_name: php-debug-cors-prometheus
    depends_on:
      - db
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-additional.ini:ro
    networks:
      - cors_dev
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
      - COMPOSER_AUTH=${COMPOSER_AUTH:-}

volumes:
  cors-prometheus-database: