_pimcore:
    resource: "@PimcoreCoreBundle/Resources/config/routing.yml"

_cors:
    resource: "@CORSPrometheusBundle/Resources/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: annotation