parameters:
    secret: pjvpZ/xL32KEEOp3bNanjpcfTetW0w2H04b78A6CXKI=

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Prometheus\Storage\Adapter:
        factory: [ 'CORS\Bundle\PrometheusBundle\StorageFactory', 'create' ]
        arguments:
            $dsn: 'redis://redis:6379'
