name: Behat
on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yaml'
      - 'README.md'
  pull_request:
    branches: [ 'main' ]
    paths-ignore:
        - 'docs/**'
        - '.github/workflows/docs.yaml'
        - 'README.md'

permissions:
  contents: read

jobs:
  docs:
    uses: coreshop/workflow-collection/.github/workflows/behat.yml@v1
