name: "Documentation"
on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'
      - 'README.md'
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'
      - 'README.md'

permissions:
  contents: read

jobs:
  docs:
    uses: coreshop/workflow-collection/.github/workflows/docs.yml@v1